---
# Setup the hosts file
- name: nginx-play | Add to /etc/hosts file
  template:  
      src: "{{ role_path }}/templates/etchosts.j2"
      dest: "/etc/hosts"
      owner: root
      group: root
      mode: 0644
  become: yes
...



